/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const ExerciseId = IDL.Nat;
export const ScheduledExercise = IDL.Record({
  'exerciseId' : ExerciseId,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'notes' : IDL.Text,
});
export const LogId = IDL.Nat;
export const CompletedExercise = IDL.Record({
  'exerciseId' : ExerciseId,
  'notes' : IDL.Text,
  'repsCompleted' : IDL.Nat,
  'setsCompleted' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const WorkoutLog = IDL.Record({
  'id' : LogId,
  'completedExercises' : IDL.Vec(CompletedExercise),
  'date' : Timestamp,
  'dayOfWeek' : DayOfWeek,
  'isActive' : IDL.Bool,
});
export const AnimationType = IDL.Variant({
  'dip' : IDL.Null,
  'mountainClimber' : IDL.Null,
  'pullUp' : IDL.Null,
  'pushUp' : IDL.Null,
  'lunge' : IDL.Null,
  'squat' : IDL.Null,
  'crunch' : IDL.Null,
  'jumpingJack' : IDL.Null,
  'generic' : IDL.Null,
  'plank' : IDL.Null,
  'burpee' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : ExerciseId,
  'estimatedDurationSeconds' : IDL.Nat,
  'animationType' : AnimationType,
  'difficulty' : Difficulty,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'muscleGroup' : MuscleGroup,
});
export const DaySchedule = IDL.Record({
  'day' : DayOfWeek,
  'exercises' : IDL.Vec(ScheduledExercise),
});
export const WeeklySchedule = IDL.Record({
  'tuesday' : DaySchedule,
  'wednesday' : DaySchedule,
  'saturday' : DaySchedule,
  'thursday' : DaySchedule,
  'sunday' : DaySchedule,
  'friday' : DaySchedule,
  'monday' : DaySchedule,
});

export const idlService = IDL.Service({
  'addExerciseToDay' : IDL.Func([DayOfWeek, ScheduledExercise], [], []),
  'finishWorkoutSession' : IDL.Func([LogId], [IDL.Bool], []),
  'getActiveWorkoutSession' : IDL.Func([], [IDL.Opt(WorkoutLog)], ['query']),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getDaySchedule' : IDL.Func([DayOfWeek], [DaySchedule], ['query']),
  'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
  'getWeeklySchedule' : IDL.Func([], [WeeklySchedule], ['query']),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getWorkoutLog' : IDL.Func([LogId], [IDL.Opt(WorkoutLog)], ['query']),
  'logExerciseCompletion' : IDL.Func(
      [LogId, CompletedExercise],
      [IDL.Bool],
      [],
    ),
  'removeExerciseFromDay' : IDL.Func([DayOfWeek, ExerciseId], [], []),
  'reorderDayExercises' : IDL.Func([DayOfWeek, IDL.Vec(ExerciseId)], [], []),
  'startWorkoutSession' : IDL.Func([DayOfWeek], [WorkoutLog], []),
  'updateDaySchedule' : IDL.Func(
      [DayOfWeek, IDL.Vec(ScheduledExercise)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const ExerciseId = IDL.Nat;
  const ScheduledExercise = IDL.Record({
    'exerciseId' : ExerciseId,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const LogId = IDL.Nat;
  const CompletedExercise = IDL.Record({
    'exerciseId' : ExerciseId,
    'notes' : IDL.Text,
    'repsCompleted' : IDL.Nat,
    'setsCompleted' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const WorkoutLog = IDL.Record({
    'id' : LogId,
    'completedExercises' : IDL.Vec(CompletedExercise),
    'date' : Timestamp,
    'dayOfWeek' : DayOfWeek,
    'isActive' : IDL.Bool,
  });
  const AnimationType = IDL.Variant({
    'dip' : IDL.Null,
    'mountainClimber' : IDL.Null,
    'pullUp' : IDL.Null,
    'pushUp' : IDL.Null,
    'lunge' : IDL.Null,
    'squat' : IDL.Null,
    'crunch' : IDL.Null,
    'jumpingJack' : IDL.Null,
    'generic' : IDL.Null,
    'plank' : IDL.Null,
    'burpee' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : ExerciseId,
    'estimatedDurationSeconds' : IDL.Nat,
    'animationType' : AnimationType,
    'difficulty' : Difficulty,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'muscleGroup' : MuscleGroup,
  });
  const DaySchedule = IDL.Record({
    'day' : DayOfWeek,
    'exercises' : IDL.Vec(ScheduledExercise),
  });
  const WeeklySchedule = IDL.Record({
    'tuesday' : DaySchedule,
    'wednesday' : DaySchedule,
    'saturday' : DaySchedule,
    'thursday' : DaySchedule,
    'sunday' : DaySchedule,
    'friday' : DaySchedule,
    'monday' : DaySchedule,
  });
  
  return IDL.Service({
    'addExerciseToDay' : IDL.Func([DayOfWeek, ScheduledExercise], [], []),
    'finishWorkoutSession' : IDL.Func([LogId], [IDL.Bool], []),
    'getActiveWorkoutSession' : IDL.Func([], [IDL.Opt(WorkoutLog)], ['query']),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getDaySchedule' : IDL.Func([DayOfWeek], [DaySchedule], ['query']),
    'getExercise' : IDL.Func([ExerciseId], [IDL.Opt(Exercise)], ['query']),
    'getWeeklySchedule' : IDL.Func([], [WeeklySchedule], ['query']),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getWorkoutLog' : IDL.Func([LogId], [IDL.Opt(WorkoutLog)], ['query']),
    'logExerciseCompletion' : IDL.Func(
        [LogId, CompletedExercise],
        [IDL.Bool],
        [],
      ),
    'removeExerciseFromDay' : IDL.Func([DayOfWeek, ExerciseId], [], []),
    'reorderDayExercises' : IDL.Func([DayOfWeek, IDL.Vec(ExerciseId)], [], []),
    'startWorkoutSession' : IDL.Func([DayOfWeek], [WorkoutLog], []),
    'updateDaySchedule' : IDL.Func(
        [DayOfWeek, IDL.Vec(ScheduledExercise)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };