/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnimationType = { 'dip' : null } |
  { 'mountainClimber' : null } |
  { 'pullUp' : null } |
  { 'pushUp' : null } |
  { 'lunge' : null } |
  { 'squat' : null } |
  { 'crunch' : null } |
  { 'jumpingJack' : null } |
  { 'generic' : null } |
  { 'plank' : null } |
  { 'burpee' : null };
export interface CompletedExercise {
  'exerciseId' : ExerciseId,
  'notes' : string,
  'repsCompleted' : bigint,
  'setsCompleted' : bigint,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface DaySchedule {
  'day' : DayOfWeek,
  'exercises' : Array<ScheduledExercise>,
}
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Exercise {
  'id' : ExerciseId,
  'estimatedDurationSeconds' : bigint,
  'animationType' : AnimationType,
  'difficulty' : Difficulty,
  'name' : string,
  'description' : string,
  'steps' : Array<string>,
  'muscleGroup' : MuscleGroup,
}
export type ExerciseId = bigint;
export type LogId = bigint;
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null };
export interface ScheduledExercise {
  'exerciseId' : ExerciseId,
  'reps' : bigint,
  'sets' : bigint,
  'notes' : string,
}
export type Timestamp = bigint;
export interface WeeklySchedule {
  'tuesday' : DaySchedule,
  'wednesday' : DaySchedule,
  'saturday' : DaySchedule,
  'thursday' : DaySchedule,
  'sunday' : DaySchedule,
  'friday' : DaySchedule,
  'monday' : DaySchedule,
}
export interface WorkoutLog {
  'id' : LogId,
  'completedExercises' : Array<CompletedExercise>,
  'date' : Timestamp,
  'dayOfWeek' : DayOfWeek,
  'isActive' : boolean,
}
export interface _SERVICE {
  'addExerciseToDay' : ActorMethod<[DayOfWeek, ScheduledExercise], undefined>,
  'finishWorkoutSession' : ActorMethod<[LogId], boolean>,
  'getActiveWorkoutSession' : ActorMethod<[], [] | [WorkoutLog]>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getDaySchedule' : ActorMethod<[DayOfWeek], DaySchedule>,
  'getExercise' : ActorMethod<[ExerciseId], [] | [Exercise]>,
  'getWeeklySchedule' : ActorMethod<[], WeeklySchedule>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutLog>>,
  'getWorkoutLog' : ActorMethod<[LogId], [] | [WorkoutLog]>,
  'logExerciseCompletion' : ActorMethod<[LogId, CompletedExercise], boolean>,
  'removeExerciseFromDay' : ActorMethod<[DayOfWeek, ExerciseId], undefined>,
  'reorderDayExercises' : ActorMethod<
    [DayOfWeek, Array<ExerciseId>],
    undefined
  >,
  'startWorkoutSession' : ActorMethod<[DayOfWeek], WorkoutLog>,
  'updateDaySchedule' : ActorMethod<
    [DayOfWeek, Array<ScheduledExercise>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];