/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: ExerciseId;
    estimatedDurationSeconds: bigint;
    animationType: AnimationType;
    difficulty: Difficulty;
    name: string;
    description: string;
    steps: Array<string>;
    muscleGroup: MuscleGroup;
}
export interface CompletedExercise {
    exerciseId: ExerciseId;
    notes: string;
    repsCompleted: bigint;
    setsCompleted: bigint;
}
export interface WorkoutLog {
    id: LogId;
    completedExercises: Array<CompletedExercise>;
    date: Timestamp;
    dayOfWeek: DayOfWeek;
    isActive: boolean;
}
export type Timestamp = bigint;
export type ExerciseId = bigint;
export interface WeeklySchedule {
    tuesday: DaySchedule;
    wednesday: DaySchedule;
    saturday: DaySchedule;
    thursday: DaySchedule;
    sunday: DaySchedule;
    friday: DaySchedule;
    monday: DaySchedule;
}
export interface ScheduledExercise {
    exerciseId: ExerciseId;
    reps: bigint;
    sets: bigint;
    notes: string;
}
export interface DaySchedule {
    day: DayOfWeek;
    exercises: Array<ScheduledExercise>;
}
export type LogId = bigint;
export enum AnimationType {
    dip = "dip",
    mountainClimber = "mountainClimber",
    pullUp = "pullUp",
    pushUp = "pushUp",
    lunge = "lunge",
    squat = "squat",
    crunch = "crunch",
    jumpingJack = "jumpingJack",
    generic = "generic",
    plank = "plank",
    burpee = "burpee"
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum Difficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum MuscleGroup {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs"
}
export interface backendInterface {
    addExerciseToDay(day: DayOfWeek, exercise: ScheduledExercise): Promise<void>;
    finishWorkoutSession(logId: LogId): Promise<boolean>;
    getActiveWorkoutSession(): Promise<WorkoutLog | null>;
    getAllExercises(): Promise<Array<Exercise>>;
    getDaySchedule(day: DayOfWeek): Promise<DaySchedule>;
    getExercise(id: ExerciseId): Promise<Exercise | null>;
    getWeeklySchedule(): Promise<WeeklySchedule>;
    getWorkoutHistory(): Promise<Array<WorkoutLog>>;
    getWorkoutLog(logId: LogId): Promise<WorkoutLog | null>;
    logExerciseCompletion(logId: LogId, completedExercise: CompletedExercise): Promise<boolean>;
    removeExerciseFromDay(day: DayOfWeek, exerciseId: ExerciseId): Promise<void>;
    reorderDayExercises(day: DayOfWeek, orderedIds: Array<ExerciseId>): Promise<void>;
    startWorkoutSession(day: DayOfWeek): Promise<WorkoutLog>;
    updateDaySchedule(day: DayOfWeek, exercises: Array<ScheduledExercise>): Promise<void>;
}
import type { AnimationType as _AnimationType, CompletedExercise as _CompletedExercise, DayOfWeek as _DayOfWeek, DaySchedule as _DaySchedule, Difficulty as _Difficulty, Exercise as _Exercise, ExerciseId as _ExerciseId, LogId as _LogId, MuscleGroup as _MuscleGroup, ScheduledExercise as _ScheduledExercise, Timestamp as _Timestamp, WeeklySchedule as _WeeklySchedule, WorkoutLog as _WorkoutLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExerciseToDay(arg0: DayOfWeek, arg1: ScheduledExercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToDay(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToDay(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async finishWorkoutSession(arg0: LogId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.finishWorkoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishWorkoutSession(arg0);
            return result;
        }
    }
    async getActiveWorkoutSession(): Promise<WorkoutLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWorkoutSession();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWorkoutSession();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDaySchedule(arg0: DayOfWeek): Promise<DaySchedule> {
        if (this.processError) {
            try {
                const result = await this.actor.getDaySchedule(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DaySchedule_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDaySchedule(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DaySchedule_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercise(arg0: ExerciseId): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercise(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercise(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySchedule(): Promise<WeeklySchedule> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySchedule();
                return from_candid_WeeklySchedule_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySchedule();
            return from_candid_WeeklySchedule_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutHistory(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutLog(arg0: LogId): Promise<WorkoutLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLog(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLog(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async logExerciseCompletion(arg0: LogId, arg1: CompletedExercise): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logExerciseCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logExerciseCompletion(arg0, arg1);
            return result;
        }
    }
    async removeExerciseFromDay(arg0: DayOfWeek, arg1: ExerciseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeExerciseFromDay(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeExerciseFromDay(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async reorderDayExercises(arg0: DayOfWeek, arg1: Array<ExerciseId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderDayExercises(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderDayExercises(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async startWorkoutSession(arg0: DayOfWeek): Promise<WorkoutLog> {
        if (this.processError) {
            try {
                const result = await this.actor.startWorkoutSession(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_WorkoutLog_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startWorkoutSession(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_WorkoutLog_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDaySchedule(arg0: DayOfWeek, arg1: Array<ScheduledExercise>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDaySchedule(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDaySchedule(to_candid_DayOfWeek_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_AnimationType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimationType): AnimationType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DaySchedule_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaySchedule): DaySchedule {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_WeeklySchedule_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeeklySchedule): WeeklySchedule {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutLog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutLog): WorkoutLog {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : from_candid_Exercise_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutLog]): WorkoutLog | null {
    return value.length === 0 ? null : from_candid_WorkoutLog_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExerciseId;
    estimatedDurationSeconds: bigint;
    animationType: _AnimationType;
    difficulty: _Difficulty;
    name: string;
    description: string;
    steps: Array<string>;
    muscleGroup: _MuscleGroup;
}): {
    id: ExerciseId;
    estimatedDurationSeconds: bigint;
    animationType: AnimationType;
    difficulty: Difficulty;
    name: string;
    description: string;
    steps: Array<string>;
    muscleGroup: MuscleGroup;
} {
    return {
        id: value.id,
        estimatedDurationSeconds: value.estimatedDurationSeconds,
        animationType: from_candid_AnimationType_n11(_uploadFile, _downloadFile, value.animationType),
        difficulty: from_candid_Difficulty_n13(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        description: value.description,
        steps: value.steps,
        muscleGroup: from_candid_MuscleGroup_n15(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    exercises: Array<_ScheduledExercise>;
}): {
    day: DayOfWeek;
    exercises: Array<ScheduledExercise>;
} {
    return {
        day: from_candid_DayOfWeek_n6(_uploadFile, _downloadFile, value.day),
        exercises: value.exercises
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: _DaySchedule;
    wednesday: _DaySchedule;
    saturday: _DaySchedule;
    thursday: _DaySchedule;
    sunday: _DaySchedule;
    friday: _DaySchedule;
    monday: _DaySchedule;
}): {
    tuesday: DaySchedule;
    wednesday: DaySchedule;
    saturday: DaySchedule;
    thursday: DaySchedule;
    sunday: DaySchedule;
    friday: DaySchedule;
    monday: DaySchedule;
} {
    return {
        tuesday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.tuesday),
        wednesday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.wednesday),
        saturday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.saturday),
        thursday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.thursday),
        sunday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.sunday),
        friday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.friday),
        monday: from_candid_DaySchedule_n17(_uploadFile, _downloadFile, value.monday)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LogId;
    completedExercises: Array<_CompletedExercise>;
    date: _Timestamp;
    dayOfWeek: _DayOfWeek;
    isActive: boolean;
}): {
    id: LogId;
    completedExercises: Array<CompletedExercise>;
    date: Timestamp;
    dayOfWeek: DayOfWeek;
    isActive: boolean;
} {
    return {
        id: value.id,
        completedExercises: value.completedExercises,
        date: value.date,
        dayOfWeek: from_candid_DayOfWeek_n6(_uploadFile, _downloadFile, value.dayOfWeek),
        isActive: value.isActive
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dip: null;
} | {
    mountainClimber: null;
} | {
    pullUp: null;
} | {
    pushUp: null;
} | {
    lunge: null;
} | {
    squat: null;
} | {
    crunch: null;
} | {
    jumpingJack: null;
} | {
    generic: null;
} | {
    plank: null;
} | {
    burpee: null;
}): AnimationType {
    return "dip" in value ? AnimationType.dip : "mountainClimber" in value ? AnimationType.mountainClimber : "pullUp" in value ? AnimationType.pullUp : "pushUp" in value ? AnimationType.pushUp : "lunge" in value ? AnimationType.lunge : "squat" in value ? AnimationType.squat : "crunch" in value ? AnimationType.crunch : "jumpingJack" in value ? AnimationType.jumpingJack : "generic" in value ? AnimationType.generic : "plank" in value ? AnimationType.plank : "burpee" in value ? AnimationType.burpee : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): Difficulty {
    return "intermediate" in value ? Difficulty.intermediate : "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
}): MuscleGroup {
    return "shoulders" in value ? MuscleGroup.shoulders : "arms" in value ? MuscleGroup.arms : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "legs" in value ? MuscleGroup.legs : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutLog>): Array<WorkoutLog> {
    return value.map((x)=>from_candid_WorkoutLog_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
